import Navbar from "@/components/Navbar";
import Background from "@/components/Background";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <div className="fixed inset-0 z-0 overflow-hidden">
            <Background />
          </div>
          <div className='relative w-full p-8 z-20'>
            <Navbar />
          </div>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
